# Test: Quantum states

In this notebook we are testing the generation of both defined and random quantum states using the QuantumState class.

In [15]:
import sys 
sys.path.append('../../')

import numpy as np
from qnn.quantum_neural_networks import StateDiscriminativeQuantumNeuralNetworks as nnd
from qnn.quantum_state import QuantumState 

In [5]:
ψ = QuantumState([np.array([1, 0])])  # Creates a QuantumState object with the defined params

In [6]:
ψ.states  # We can access the states

[array([1, 0])]

In [7]:
ψ.probabilities  # And the probabilities

[1.0]

In [8]:
ρ = QuantumState([np.array([1, 0]), np.array([1, 1])/np.sqrt(2)])  # Creates a QuantumState object with the defined params

In [9]:
ρ.states  # We can access the states

[array([1, 0]), array([0.70710678, 0.70710678])]

In [10]:
ρ.probabilities  # And the probabilities

[0.5, 0.5]

In [11]:
σ = QuantumState.random(5)  # Creates a QuantumState object with n random quantum states

In [12]:
σ.states

[array([0.65687294+0.25382368j, 0.63501031-0.31757422j]),
 array([-0.08881865-0.06155179j, -0.82971799+0.54762276j]),
 array([ 0.52065116-0.37998698j, -0.28506059+0.70941717j]),
 array([-0.00471883+0.0457426j , -0.18059838-0.98248133j]),
 array([-0.58991007+0.18699008j,  0.77807802-0.10786754j])]