In [10]:
import sys 
sys.path.append('../')

import numpy as np
from quantum_neural_networks import StateDiscriminativeQuantumNeuralNetworks as nnd
from quantum_neural_networks import QuantumState 

In [2]:
ψ = QuantumState( [ np.array([1, 0]) ] )

In [3]:
ψ.states

[array([1, 0])]

In [4]:
ψ.probabilities

[1.0]

In [5]:
ρ = QuantumState( [ np.array([1, 0]), np.array([1, 1])/np.sqrt(2) ] )

In [6]:
ρ.states

[array([1, 0]), array([0.70710678, 0.70710678])]

In [7]:
ρ.probabilities

[0.5, 0.5]

In [8]:
σ = QuantumState.random(5)

In [9]:
σ.states

[array([0.99482323-0.07686541j, 0.06559621+0.01075097j]),
 array([-0.63143166-0.02644322j, -0.49960427-0.59244441j]),
 array([-0.52759444+0.76996142j, -0.14535976-0.32813725j]),
 array([-0.65810193+0.29063705j,  0.44209071-0.53571239j]),
 array([ 0.04513703-0.47343337j, -0.59593964-0.64705443j])]