# Test: Quantum states

In this notebook we are testing the generation of both defined and random quantum states using the QuantumState class.

In [1]:
import sys

sys.path.append('../../')

import numpy as np
from qnn.quantum_neural_networks import StateDiscriminativeQuantumNeuralNetworks as nnd
from qnn.quantum_state import QuantumState

In [2]:
# Creates a QuantumState object with the defined params
ψ = QuantumState([np.array([1, 0])])  

In [3]:
# We can access the states
ψ.states  

[array([1, 0])]

In [4]:
# And the probabilities
ψ.probabilities  

[1.0]

In [5]:
# Creates a QuantumState object with the defined params
ρ = QuantumState([np.array([1, 0]), np.array([1, 1]) / np.sqrt(2)])  

# We can access the states
ρ.states 

[array([1, 0]), array([0.70710678, 0.70710678])]

In [6]:
# And the probabilities
ρ.probabilities 

[0.5, 0.5]

In [9]:
# Creates a QuantumState object with n random quantum states
σ = QuantumState.random(5)  
σ.states

[array([ 0.80258079+0.55848499j, -0.16606844-0.12798387j]),
 array([ 0.75991186+0.20190476j, -0.16484282-0.59547903j]),
 array([0.43808171+0.4515078j , 0.30794218-0.71372035j]),
 array([-0.51169969+0.60012034j, -0.01003507+0.6147506j ]),
 array([0.04500584+0.50050378j, 0.31191755+0.80633609j])]